[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn travel_agency.wsgi:application --bind 0.0.0.0:$PORT"
