# Generated by Django 5.2.4 on 2025-08-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accommodation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='airport_transfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='availability_calendar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='booking_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('expert', 'Expert')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size_max',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size_min',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='group_size_recommended',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='package',
            name='important_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='meal_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='seasonal_pricing_off_peak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='seasonal_pricing_peak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='seasonal_pricing_shoulder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='transportation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weather_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='what_to_bring',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('included', models.BooleanField(default=True)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.package')),
            ],
            options={
                'verbose_name_plural': 'Package activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='Days at this destination')),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='api.package')),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded'), ('optional', 'Optional')], max_length=20)),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='api.package')),
            ],
            options={
                'ordering': ['category', 'item'],
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activities', models.JSONField(default=list)),
                ('meals', models.JSONField(default=list)),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('transportation', models.CharField(blank=True, max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.package')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('package', 'day')},
            },
        ),
    ]
