# Generated by Django 5.2.4 on 2025-08-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homepagecontent_homepagectasection_homepagefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('image_type', models.CharField(choices=[('hero', 'Hero Background'), ('feature', 'Feature Image'), ('testimonial', 'Testimonial Image'), ('gallery', 'Gallery Image')], default='gallery', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Image',
                'verbose_name_plural': 'Homepage Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='background_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional background images for rotation'),
        ),
    ]
