# Generated by Django 5.2.4 on 2025-08-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ferryschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True),
        ),
    ]
