# Generated by Django 5.2.4 on 2025-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_page_og_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for content management'),
        ),
    ]
