# Generated by Django 5.2.4 on 2025-08-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_type', models.CharField(choices=[('water_sports', 'Water Sports'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('wellness', 'Wellness'), ('food', 'Food & Dining'), ('photography', 'Photography'), ('fishing', 'Fishing'), ('diving', 'Diving & Snorkeling'), ('sailing', 'Sailing & Cruises'), ('spa', 'Spa & Relaxation')], max_length=50)),
                ('duration', models.CharField(help_text="e.g., '2 hours', 'Full day'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('min_age', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('expert', 'Expert')], default='easy', max_length=20)),
                ('includes', models.JSONField(default=list, help_text="List of what's included")),
                ('excludes', models.JSONField(default=list, help_text="List of what's not included")),
                ('requirements', models.JSONField(default=list, help_text='List of requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.destination')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.location')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
