# Generated by Django 5.2.4 on 2025-08-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('transportation', 'Transportation Page'), ('map', 'Map Page'), ('faq', 'FAQ Page'), ('blog', 'Blog Page'), ('packages', 'Packages Page'), ('properties', 'Properties Page')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='page_heroes/')),
                ('background_image_url', models.URLField(blank=True, null=True)),
                ('overlay_opacity', models.FloatField(default=0.6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Heroes',
            },
        ),
    ]
