# Generated by Django 5.2.4 on 2025-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.TextField(blank=True, help_text='Package highlights, one per line or separated by commas'),
        ),
    ]
