# Generated by Django 5.2.4 on 2025-08-25 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_package_highlights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'ru', 'zh')", max_length=10, unique=True)),
                ('name', models.CharField(help_text='Language name in English', max_length=100)),
                ('native_name', models.CharField(help_text='Language name in native script', max_length=100)),
                ('flag', models.CharField(help_text='Flag emoji or icon', max_length=10)),
                ('direction', models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], default='ltr', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Translation key (e.g., 'homepage.hero.title')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this key is used for')),
                ('context', models.CharField(blank=True, help_text='Context where this translation is used', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Translation Key',
                'verbose_name_plural': 'Translation Keys',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.AddField(
            model_name='destination',
            name='localized_description',
            field=models.TextField(blank=True, help_text='Localized description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='localized_name',
            field=models.CharField(blank=True, help_text='Localized name if different from base name', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='localized_description',
            field=models.TextField(blank=True, help_text='Localized description'),
        ),
        migrations.AddField(
            model_name='package',
            name='localized_highlights',
            field=models.JSONField(blank=True, default=list, help_text='Localized highlights'),
        ),
        migrations.AddField(
            model_name='package',
            name='localized_included',
            field=models.JSONField(blank=True, default=list, help_text='Localized included items'),
        ),
        migrations.AddField(
            model_name='package',
            name='localized_name',
            field=models.CharField(blank=True, help_text='Localized package name', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='localized_amenities',
            field=models.JSONField(blank=True, default=list, help_text='Localized amenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='localized_description',
            field=models.TextField(blank=True, help_text='Localized description'),
        ),
        migrations.AddField(
            model_name='property',
            name='localized_name',
            field=models.CharField(blank=True, help_text='Localized property name', max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='api.language'),
        ),
        migrations.AddField(
            model_name='package',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.language'),
        ),
        migrations.AddField(
            model_name='property',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.language'),
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('name', 'language')},
        ),
        migrations.CreateModel(
            name='LocalizedFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_faqs', to='api.language')),
            ],
            options={
                'verbose_name': 'Localized FAQ',
                'verbose_name_plural': 'Localized FAQs',
                'ordering': ['language__code', 'category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CulturalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('customs', 'Local Customs'), ('etiquette', 'Etiquette'), ('language', 'Language Tips'), ('currency', 'Currency Information'), ('weather', 'Weather Information'), ('transportation', 'Transportation Tips'), ('food', 'Food & Dining'), ('safety', 'Safety Information'), ('emergency', 'Emergency Information'), ('holidays', 'Holidays & Events')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_content', to='api.language')),
            ],
            options={
                'verbose_name': 'Cultural Content',
                'verbose_name_plural': 'Cultural Content',
                'ordering': ['language__code', 'content_type', 'order'],
                'unique_together': {('language', 'content_type', 'title')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('faq', 'FAQ Page'), ('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy'), ('cancellation', 'Cancellation Policy'), ('refund', 'Refund Policy'), ('custom', 'Custom Page')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_pages', to='api.language')),
            ],
            options={
                'verbose_name': 'Localized Page',
                'verbose_name_plural': 'Localized Pages',
                'ordering': ['language__code', 'page_type'],
                'unique_together': {('language', 'page_type')},
            },
        ),
        migrations.CreateModel(
            name='RegionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='USD', help_text='ISO currency code', max_length=3)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol', max_length=5)),
                ('date_format', models.CharField(default='MM/DD/YYYY', help_text='Date format', max_length=20)),
                ('time_format', models.CharField(choices=[('12', '12-hour'), ('24', '24-hour')], default='12', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone', max_length=50)),
                ('phone_format', models.CharField(blank=True, help_text='Phone number format', max_length=50)),
                ('address_format', models.TextField(blank=True, help_text='Address format template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_settings', to='api.language')),
            ],
            options={
                'verbose_name': 'Regional Settings',
                'verbose_name_plural': 'Regional Settings',
                'unique_together': {('language',)},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Translated text')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this translation has been approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations_created', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.language')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.translationkey')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key__key', 'language__code'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
