# Generated by Django 5.2.4 on 2025-08-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_language_translationkey_alter_package_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AlterField(
            model_name='experience',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.destination'),
        ),
    ]
