# Generated by Django 5.2.4 on 2025-08-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_experience_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='properties',
        ),
        migrations.AlterField(
            model_name='experience',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.destination'),
        ),
    ]
