# Generated by Django 5.2.4 on 2025-08-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_package_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('story', 'Our Story Section'), ('values', 'Our Values Section'), ('stats', 'Statistics Section'), ('why_choose', 'Why Choose Us Section'), ('cta', 'Call to Action Section')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Statistic',
                'verbose_name_plural': 'About Page Statistics',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Value',
                'verbose_name_plural': 'About Page Values',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Override destination name if needed', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Custom description for homepage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_destinations/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative image URL', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_homepage', to='api.destination')),
            ],
            options={
                'verbose_name': 'Featured Destination',
                'verbose_name_plural': 'Featured Destinations',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
